var ICONS = {
  "Banjo & Kazooie": "https://www.ssbwiki.com/images/1/12/Banjo%26KazooieHeadSSBUWebsite.png",
  "Bayonetta":"https://www.ssbwiki.com/images/2/27/BayonettaHeadSSBUWebsite.png",
  "Bowser":"https://www.ssbwiki.com/images/0/0b/BowserHeadSSBUWebsite.png",
  "Bowser Jr.": "https://www.ssbwiki.com/images/3/3e/BowserJrHeadSSBUWebsite.png",
  "Byleth": "https://www.ssbwiki.com/images/8/86/BylethHeadSSBUWebsite.png",
  "Captain Falcon": "https://www.ssbwiki.com/images/6/6b/CaptainFalconHeadSSBUWebsite.png",
  "Chrom": "https://www.ssbwiki.com/images/7/70/ChromHeadSSBUWebsite.png",
  "Cloud": "https://www.ssbwiki.com/images/c/cb/CloudHeadSSBUWebsite.png",
  "Corrin": "https://www.ssbwiki.com/images/6/6a/CorrinHeadSSBUWebsite.png",
  "Daisy": "https://www.ssbwiki.com/images/2/2d/DaisyHeadSSBUWebsite.png",
  "Dark Pit": "https://www.ssbwiki.com/images/8/8b/DarkPitHeadSSBUWebsite.png",
  "Dark Samus": "https://www.ssbwiki.com/images/2/24/DarkSamusHeadSSBUWebsite.png",
  "Diddy Kong": "https://www.ssbwiki.com/images/5/5d/DiddyKongHeadSSBUWebsite.png",
  "Donkey Kong":"https://www.ssbwiki.com/images/2/21/DonkeyKongHeadSSBUWebsite.png",
  "Dr. Mario": "https://www.ssbwiki.com/images/c/c8/DrMarioHeadSSBUWebsite.png",
  "Duck Hunt Duo": "https://www.ssbwiki.com/images/3/38/DuckHuntHeadSSBUWebsite.png",
  "Falco":"https://www.ssbwiki.com/images/6/6e/FalcoHeadSSBUWebsite.png",
  "Fox": "https://www.ssbwiki.com/images/c/c9/FoxHeadSSBUWebsite.png",
  "Ganondorf": "https://www.ssbwiki.com/images/b/b6/GanondorfHeadSSBUWebsite.png",
  "Greninja": "https://www.ssbwiki.com/images/7/79/GreninjaHeadSSBUWebsite.png",
  "Hero": "https://www.ssbwiki.com/images/1/1e/HeroHeadSSBUWebsite.png",
  "Ice Climbers": "https://www.ssbwiki.com/images/0/0c/IceClimbersHeadSSBUWebsite.png",
  "Ike": "https://www.ssbwiki.com/images/2/25/IkeHeadSSBUWebsite.png",
  "Incineroar": "https://www.ssbwiki.com/images/e/e3/IncineroarHeadSSBUWebsite.png",
  "Inkling": "https://www.ssbwiki.com/images/0/04/InklingHeadSSBUWebsite.png",
  "Isabelle": "https://www.ssbwiki.com/images/2/2e/IsabelleHeadSSBUWebsite.png",
  "Jigglypuff": "https://www.ssbwiki.com/images/9/90/JigglypuffHeadSSBUWebsite.png",
  "Joker": "https://www.ssbwiki.com/images/6/63/JokerHeadSSBUWebsite.png",
  "Ken": "https://www.ssbwiki.com/images/e/ef/KenHeadSSBUWebsite.png",
  "King Dedede": "https://www.ssbwiki.com/images/f/fe/KingDededeHeadSSBUWebsite.png",
  "King K. Rool":"https://www.ssbwiki.com/images/3/35/KingKRoolHeadSSBUWebsite.png",
  "Kirby":"https://www.ssbwiki.com/images/1/15/KirbyHeadSSBUWebsite.png",
  "Link": "https://www.ssbwiki.com/images/2/2b/LinkHeadSSBUWebsite.png",
  "Little Mac": "https://www.ssbwiki.com/images/8/87/LittleMacHeadSSBUWebsite.png",
  "Lucario":"https://www.ssbwiki.com/images/2/20/LucarioHeadSSBUWebsite.png",
  "Lucas": "https://www.ssbwiki.com/images/3/31/LucasHeadSSBUWebsite.png",
  "Lucina": "https://www.ssbwiki.com/images/d/d8/LucinaHeadSSBUWebsite.png",
  "Luigi": "https://www.ssbwiki.com/images/9/9d/LuigiHeadSSBUWebsite.png",
  "Mario": "https://www.ssbwiki.com/images/9/9e/MarioHeadSSBUWebsite.png",
  "Marth": "https://www.ssbwiki.com/images/a/ae/MarthHeadSSBUWebsite.png",
  "Mega Man": "https://www.ssbwiki.com/images/2/26/MegaManHeadSSBUWebsite.png",
  "Metaknight": "https://www.ssbwiki.com/images/3/3d/MetaKnightHeadSSBUWebsite.png",
  "Mewtwo": "https://www.ssbwiki.com/images/7/7e/MewtwoHeadSSBUWebsite.png",
  "Mii Brawler": "https://www.ssbwiki.com/images/d/d8/MiiBrawlerHeadSSBU.png",
  "Mii Gunner": "https://www.ssbwiki.com/images/3/3d/MiiGunnerHeadSSBU.png",
  "Mii Swordfighter": "https://www.ssbwiki.com/images/e/ef/MiiSwordfighterHeadSSBU.png",
  "Mr. Game and Watch": "https://www.ssbwiki.com/images/1/15/MrGame%26WatchHeadSSBUWebsite.png",
  "Ness": "https://www.ssbwiki.com/images/d/d5/NessHeadSSBUWebsite.png",
  "Pac-Man": "https://www.ssbwiki.com/images/3/3d/Pac-ManHeadSSBUWebsite.png",
  "Palutena":"https://www.ssbwiki.com/images/d/d7/PalutenaHeadSSBUWebsite.png",
  "Peach": "https://www.ssbwiki.com/images/1/14/PeachHeadSSBUWebsite.png",
  "Pichu": "https://www.ssbwiki.com/images/5/50/PichuHeadSSBUWebsite.png",
  "Pikachu": "https://www.ssbwiki.com/images/5/52/PikachuHeadSSBUWebsite.png",
  "Pikmin & Olimar": "https://www.ssbwiki.com/images/9/97/OlimarHeadSSBUWebsite.png",
  "Piranha Plant": "https://www.ssbwiki.com/images/c/cf/PiranhaPlantHeadSSBUWebsite.png",
  "Pit": "https://www.ssbwiki.com/images/d/d7/PitHeadSSBUWebsite.png",
  "Pokémon Trainer": "https://www.ssbwiki.com/images/2/2c/Pok%C3%A9monTrainerHeadSSBUWebsite.png",
  "Random": "?",
  "Richter":"https://www.ssbwiki.com/images/a/ab/RichterHeadSSBUWebsite.png",
  "Ridley": "https://www.ssbwiki.com/images/7/7c/RidleyHeadSSBUWebsite.png",
  "ROB": "https://www.ssbwiki.com/images/b/be/ROBHeadSSBUWebsite.png",
  "Robin": "https://www.ssbwiki.com/images/4/43/RobinHeadSSBUWebsite.png",
  "Rosalina & Luma": "https://www.ssbwiki.com/images/6/63/RosalinaHeadSSBUWebsite.png",
  "Roy": "https://www.ssbwiki.com/images/2/22/RoyHeadSSBUWebsite.png",
  "Ryu": "https://www.ssbwiki.com/images/2/20/RyuHeadSSBUWebsite.png",
  "Samus": "https://www.ssbwiki.com/images/d/d0/SamusHeadSSBUWebsite.png",
  "Sheik": "https://www.ssbwiki.com/images/1/1e/SheikHeadSSBUWebsite.png",
  "Shulk": "https://www.ssbwiki.com/images/b/bf/ShulkHeadSSBUWebsite.png",
  "Simon": "https://www.ssbwiki.com/images/5/52/SimonHeadSSBUWebsite.png",
  "Snake": "https://www.ssbwiki.com/images/9/9f/SnakeHeadSSBUWebsite.png",
  "Sonic": "https://www.ssbwiki.com/images/b/b7/SonicHeadSSBUWebsite.png",
  "Terry": "https://www.ssbwiki.com/images/2/2e/TerryHeadSSBUWebsite.png",
  "Toon Link": "https://www.ssbwiki.com/images/b/bf/ToonLinkHeadSSBUWebsite.png",
  "Villager": "https://www.ssbwiki.com/images/f/f9/VillagerHeadSSBUWebsite.png",
  "Wario": "https://www.ssbwiki.com/images/7/7f/WarioHeadSSBUWebsite.png",
  "Wii Fit Trainer": "https://www.ssbwiki.com/images/f/fc/WiiFitTrainerHeadSSBUWebsite.png",
  "Wolf": "https://www.ssbwiki.com/images/0/06/WolfHeadSSBUWebsite.png",
  "Yoshi": "https://www.ssbwiki.com/images/9/93/YoshiHeadSSBUWebsite.png",
  "Young Link": "https://www.ssbwiki.com/images/c/c0/YoungLinkHeadSSBUWebsite.png",
  "Zelda": "https://www.ssbwiki.com/images/c/c8/ZeldaHeadSSBUWebsite.png",
  "Zero Suit Samus":"https://www.ssbwiki.com/images/5/5a/ZeroSuitSamusHeadSSBUWebsite.png",
};

var COLOURS = {'Banjo & Kazooie': '#fcdd76', 'Bayonetta': '#a5a1e0', 'Bowser': '#44745e', 'Bowser Jr.': '#59bf38', 'Byleth': '#cee0d4', 'Captain Falcon': '#8e8adc', 'Chrom': '#b4b4cf', 'Cloud': '#419384', 'Corrin': '#63a7c0', 'Daisy': '#f0bb2c', 'Dark Pit': '#875cbe', 'Dark Samus': '#3d395e', 'Diddy Kong': '#e05a52', 'Donkey Kong': '#f9da4a', 'Dr. Mario': '#e86c6d', 'Duck Hunt Duo': '#8c5d3a', 'Falco': '#69b0de', 'Fox': '#307cdf', 'Ganondorf': '#7974a4', 'Greninja': '#5673a5', 'Hero': '#ccb3f4', 'Ice Climbers': '#a0cafe', 'Ike': '#b64f3e', 'Incineroar': '#ffd902', 'Inkling': '#f02d7d', 'Isabelle': '#c4d37e', 'Jigglypuff': '#f29bf6', 'Joker': '#b41201', 'Ken': '#cdd7dc', 'King Dedede': '#fce87b', 'King K. Rool': '#65873b', 'Kirby': '#fed6e3', 'Link': '#1c94c3', 'Little Mac': '#5d8f72', 'Lucario': '#b8e3fc', 'Lucas': '#e06833', 'Lucina': '#7ea6c7', 'Luigi': '#5ea444', 'Mario': '#ff4026', 'Marth': '#5da8c8', 'Mega Man': '#86c1e0', 'Metaknight': '#5367b0', 'Mewtwo': '#927bc5', 'Mii Brawler': '#5dc1e6', 'Mii Gunner': '#5dc1e6', 'Mii Swordfighter': '#5dc1e6', 'Mr. Game and Watch': '#a4a190', 'Ness': '#de413d', 'Pac-Man': '#fcb541', 'Palutena': '#91e5c1', 'Peach': '#f5c9f0', 'Pichu': '#dedc1f', 'Pikachu': '#ffb912', 'Pikmin & Olimar': '#ccefb0', 'Piranha Plant': '#00aa82', 'Pit': '#acdafa', 'Pokémon Trainer': '#ffc004', 'Random': '#000000', 'Richter': '#2a6db0', 'Ridley': '#71456f', 'ROB': '#b2b8bd', 'Robin': '#c387d9', 'Rosalina & Luma': '#98d5cd', 'Roy': '#74b65b', 'Ryu': '#d0504d', 'Samus': '#353f56', 'Sheik': '#756fd0', 'Shulk': '#d5647a', 'Simon': '#76150e', 'Snake': '#658198', 'Sonic': '#659deb', 'Terry': '#6eb5ff', 'Toon Link': '#8ce689', 'Villager': '#83a88e', 'Wario': '#fee71f', 'Wii Fit Trainer': '#99d481', 'Wolf': '#cccccc', 'Yoshi': '#83cd65', 'Young Link': '#a5d160', 'Zelda': '#fdeaa4', 'Zero Suit Samus': '#205ba4'};
var CHARACTERS = ["Bayonetta", "Bowser", "Bowser Jr.", "Captain Falcon", "Chrom", "Cloud", "Corrin", "Daisy", "Dark Pit", "Dark Samus", "Diddy Kong", "Donkey Kong", "Dr. Mario", "Duck Hunt Duo", "Falco", "Fox", "Ganondorf", "Greninja", "Ice Climbers", "Ike", "Incineroar", "Inkling", "Isabelle", "Jigglypuff", "Ken", "King Dedede", "King K. Rool", "Kirby", "Link", "Little Mac", "Lucario", "Lucas", "Lucina", "Luigi", "Mario", "Marth", "Mega Man", "Metaknight", "Mewtwo", "Mii Brawler", "Mii Gunner", "Mii Swordfighter", "Mr. Game and Watch", "Ness", "Pac-Man", "Palutena", "Peach", "Pichu", "Pikachu", "Pikmin & Olimar", "Pit", "Pokémon Trainer", "Random", "Richter", "Ridley", "ROB", "Robin", "Rosalina & Luma", "Roy", "Ryu", "Samus", "Sheik", "Shulk", "Simon", "Snake", "Sonic", "Toon Link", "Villager", "Wario", "Wii Fit Trainer", "Wolf", "Yoshi", "Young Link", "Zelda", "Zero Suit Samus", "Piranha Plant", "Joker", "Hero", "Banjo & Kazooie", "Terry", "Byleth"];
var STATE_COLOURS = {'QLD':'#ff7d7d', 'VIC':'#ffd263', 'NSW':'#fae634', 'SA':'#aeff9c', "ACT":'#63aaff', "WA":'#ff94fc', 'NT':'#ff94fc', "TAS":'#99ffdb',"NZ":'#3b3b3b', 'INT':'#ff8861'}